{
 "title": "Internet Speed",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Download Speed",
   "type": "graph",
   "gridPos": { "h": 10, "w": 21, "x": 1, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(download_speed[5m])",
     "legendFormat": "Speed in Mbits/s"
    }
   ]
  },
  {
   "title": "Slow or No Internet",
   "type": "graph",
   "gridPos": { "h": 6, "w": 21, "x": 1, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(avg_over_time(download_speed[5m]) < 5) + 1",
     "legendFormat": "Speed >=1 AND <= 5 Mbits/s where 1 = no internet"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 1, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "avg_over_time(latency[5m])", "legendFormat": "latency in ms" }
   ]
  },
  {
   "title": "Upload Speed",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 11, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(upload_speed[5m])",
     "legendFormat": "Speed in Mbits/s"
    }
   ]
  }
 ]
}